<a href="https://colab.research.google.com/github/LizethMesaC/Curso-Ciencia-de-Datos-UDEM/blob/main/tarea_01_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [ ]:
# Tu respuesta aquí
nombre='Ana'
edad='22'
print(f"Hola, me llamo {nombre} y tengo {edad} años.")

Hola, me llamo Ana y tengo 22 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [ ]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí

#Imprime el primer y el último elemento.
primer_numero=numeros[0]
ultimo_numero=numeros[-1]
print(f"El primer número es {primer_numero}")
print(f"El último número es {ultimo_numero}")

#Imprime los tres primeros elementos usando slicing.
tres_primeros_numeros=numeros[:3]
print(f"Los tres primeros numeros son {tres_primeros_numeros}")

#Agrega el número 99 al final de la lista.
numeros.append(99)
print(numeros)


El primer número es 10
El último número es 15
Los tres primeros numeros son [10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [ ]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"]>=6:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [ ]:
# Tu respuesta aquí
base=5
altura=8
def calcular_area(base,altura):
    area=base*altura/2
    return area
print(calcular_area(base,altura))


20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [ ]:
# Tu respuesta aquí
cuadrados=[x**2 for x in range(1,11)]
print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [ ]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [30]:
# Tu respuesta aquí
#Un arreglo con los valores [1.5, 2.5, 3.5, 4.5]
arreglo=np.array([1.5,2.5,3.5,4.5])
print(arreglo)
print("Shape Arreglo:", arreglo.shape)
print("Dtype Arreglo:", arreglo.dtype)

#Una matriz de ceros de 3 filas × 4 columnas
matriz=np.zeros((3,4))
print("\nMatriz:\n", matriz)
print("Shape Matriz:", matriz.shape)
print("Dtype Matriz:", matriz.dtype)

#Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando linspace)
arreglo_linspace=np.linspace(0,1,6)
print("\n",arreglo_linspace)
print("Shape Arreglo Linspace:", arreglo_linspace.shape)
print("Dtype Arreglo Linspace:", arreglo_linspace.dtype)

[1.5 2.5 3.5 4.5]
Shape Arreglo: (4,)
Dtype Arreglo: float64

Matriz:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape Matriz: (3, 4)
Dtype Matriz: float64

 [0.  0.2 0.4 0.6 0.8 1. ]
Shape Arreglo Linspace: (6,)
Dtype Arreglo Linspace: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [34]:
a = np.arange(1, 13)

# Tu respuesta aquí
matriz_2=a.reshape((3,4))
print("\nMatriz:\n", matriz_2)
print("Valor Máximo:", matriz_2.max())
print("Valor Mínimo:", matriz_2.min())
print("Posición del Máximo:", matriz_2.argmax())


Matriz:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Valor Máximo: 12
Valor Mínimo: 1
Posición del Máximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [38]:
# Tu respuesta aquí
arreglo1=np.random.randint(1,20,5)
arreglo2=np.random.randint(1,20,5)
print("\nArreglo 1:\n", arreglo1)
print("\nArreglo 2:\n", arreglo2)

suma=arreglo1+arreglo2
print("\nSuma:\n", suma)

resta=arreglo1-arreglo2
print("\nResta:\n", resta)

multiplicacion=arreglo1*arreglo2
print("\nMultiplicación:\n", multiplicacion)


Arreglo 1:
 [11 15  9 11  5]

Arreglo 2:
 [ 5 15 18  3 13]

Suma:
 [16 30 27 14 18]

Resta:
 [ 6  0 -9  8 -8]

Multiplicación:
 [ 55 225 162  33  65]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [39]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
notas_mayores_igual_6=notas[notas>=6]
print("\nNotas mayores o iguales a 6:\n",notas_mayores_igual_6)
#


Notas mayores o iguales a 6:
 [ 8.5  6.   9.2  7.8 10. ]
